# (C) Copyright 2020 IBM. All Rights Reserved.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

notifications:
  email: false

# Disable double triggering when issuing a PR from a branch in the main repo.
# branches:
#   only:
#     - "master"

# sudo: required // Sudo is deprecated

language: python

services: docker

# Setup Travis to use Ubuntu 18.04 - Bionic
os:
  - osx

stages:
  - Build OSX wheels

jobs:
  include:
  - name: "Build wheel for Python 3.6, 3.7, 3.8 on OS X"
    os: osx
    stage: Build OSX wheels
    # if: tag IS present
    addons:
      homebrew:
        packages:
          - openblas
        update: true
    env:
      - CIBW_BEFORE_ALL=""
      - CIBW_BEFORE_BUILD="pip install ../delocate && pip install -r requirements.txt"
      - CIBW_BUILD="cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64"
      # - CIBW_SKIP="cp27-* cp35-* cp38-*"
      # - CIBW_TEST_COMMAND="pytest -v -s tests/"
    before_install:
      - git clone -b aihwkit git@github.com:filemaster/delocate.git
    install:
      - python3 -m pip install cibuildwheel==1.6.0
    script:
      # build the wheels, put them into './wheelhouse'
      - python3 -m cibuildwheel --output-dir wheelhouse --platform macos
      # The plan is to upload the wheels via twine only when the commit is tagged
      # python3 -m twine <..>
